# Generated by Django 6.0.4 on 2026-05-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('xml_base', models.TextField()),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('xml_submetido', models.TextField()),
                ('resultado', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-data_submissao'],
            },
        ),
    ]
