# Generated by Django 6.0.4 on 2026-05-05 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corretor', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.professor'),
        ),
        migrations.AddField(
            model_name='submissao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='submissao',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretor.exercicio'),
        ),
    ]
